PROFILES = [
    {"role": "Senior Software Engineer",          "stack": "Python, FastAPI, PostgreSQL, Docker"},
    {"role": "Software Engineer",                 "stack": "JavaScript, React, Node.js, MongoDB"},
    {"role": "Software Engineer",                 "stack": "Java, Spring Boot, Kubernetes, AWS"},
    {"role": "Junior Software Engineer",          "stack": "Python, Django, REST APIs, Git"},
    {"role": "Full Stack Developer",              "stack": "TypeScript, Next.js, Prisma, Tailwind"},
    {"role": "Full Stack Developer",              "stack": "Vue.js, Laravel, MySQL, Redis"},
    {"role": "Backend Engineer",                  "stack": "Go, gRPC, PostgreSQL, GCP"},
    {"role": "Mobile Developer",                  "stack": "React Native, TypeScript, Firebase"},
    {"role": "ML Engineer",                       "stack": "Python, PyTorch, HuggingFace, MLflow"},
    {"role": "Data Scientist",                    "stack": "Python, scikit-learn, Pandas, Spark"},
    {"role": "Data Scientist",                    "stack": "R, Python, TensorFlow, BigQuery"},
    {"role": "AI Research Engineer",              "stack": "Python, JAX, LangChain, vector databases"},
    {"role": "DevOps Engineer",                   "stack": "AWS, Terraform, Kubernetes, GitHub Actions"},
    {"role": "Cloud Infrastructure Engineer",     "stack": "GCP, Pulumi, Docker, Prometheus"},
    {"role": "Site Reliability Engineer",         "stack": "Linux, Python, Datadog, Helm, Ansible"},
    {"role": "Product Manager",                   "stack": "Agile, Jira, Figma, SQL, A/B testing"},
    {"role": "Senior Product Manager",            "stack": "OKRs, Roadmapping, Mixpanel, Fintech"},
    {"role": "Technical Product Manager",         "stack": "APIs, SQL, Confluence, RICE framework"},
    {"role": "UX Designer",                       "stack": "Figma, user research, prototyping"},
    {"role": "UI/UX Designer",                    "stack": "Figma, Adobe XD, motion design"},
    {"role": "Product Designer",                  "stack": "Figma, Principle, Hotjar, conversion"},
    {"role": "Data Analyst",                      "stack": "SQL, Python, Power BI, dbt, Snowflake"},
    {"role": "Business Intelligence Analyst",     "stack": "Tableau, SQL, Excel, Salesforce"},
    {"role": "QA Engineer",                       "stack": "Selenium, Cypress, pytest, CI/CD"},
    {"role": "QA Lead",                           "stack": "Playwright, k6, TestRail, API testing"},
]